name: Docker Image CI

on:
  push:
    branches: [ master ]
  schedule:
    - cron: "2 0 1 * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out source
      uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_ID }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
#    - name: Builder instance name
#      run: echo ${{ steps.buildx.outputs.name }}
#    - name: Available platforms
#      run: echo ${{ steps.buildx.outputs.platforms }}  
    - name: Docker build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_ID }}/chrony:latest,${{ secrets.DOCKER_ID }}/chrony:${{ github.run_id }}.${{ github.run_number }}
 #   - name: Image digest
 #     run: echo ${{ steps.docker_build.outputs.digest }}
